env:
  jest: true
  browser: true
  node: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'
  - 'plugin:prettier/recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - eslint-comments
settings:
  react:
     version: 'detect'
rules:
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - never
  'no-unused-vars': 'off'
  'react/prop-types': 0
